"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import Link from "next/link"
import { useState } from 'react'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Arrow/>
        <div className="navbar">
          <Link href="/">home</Link>
          <Link href="/button">button</Link>
          <Link href="/object">object</Link>
          <Link href="/mongo">mongo</Link>
        </div>
        <Fab/>
        {children}
      </body>
    </html>
  )
}

function Arrow() {
  return (
    <Link href="/">
      <div className="arrow">
        <div className="one"></div>
        <div className="two"></div>
        <div className="three"></div>
      </div>
    </Link>
  )
}

function Fab() {
  let [isIn, setisIn] = useState(0)
  let linkList=["object", "button", "main"]
  return (
    <div onMouseEnter={()=>{setisIn(1)}}onMouseLeave={()=>{setisIn(0)}}>
      <div className="menubar" style={isIn==1?{"display":"inline"}:{"display":"none"}}>
        <div className="menu_bottom">
        {
          linkList.map((ai, i)=> {
            return (
              <div className="menu_column">
                <Link href={ai==="main"?"/":"/"+ai}>{ai}</Link>
              </div>
            )
          })
        }
        </div>
        <div className="menu_top"/>
      </div>
      <div className="fab"/>
    </div>
  )
}